version: "3.9"

services:

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s

  web:
    build: .
    container_name: django_app
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

volumes:
  mysql_data: